theme: jekyll-theme-slate

markdown: kramdown

title: [FooMan's land]
description: [Bart Vandewoestyne's blog on software development.]

disqus:
  shortname: foomansland

gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
